name: Lint Test

on:
  push:
    branches-ignore: [ development ]
  #   # Remove the line above to run when pushing to master
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Test
        uses: github/super-linter@slimv4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}